### ISSUE TITLE
好像我的自动更新配置还是错的

### ISSUE THREAD

**Issue by lychichem** [lychichem/Firefox-zh-CN-locale#13]
@yfdyh000 @wenketel 你们懂的看下我 install.rdf 和 update.rdf 哪里写错了导致不能自动从小于44.0a1-20151006的版本号更新到这个版本号

**Comment by yfdyh000** [comment]
具体是哪个版本不行？修改成 44.0a1-20151005 和 44.0a1-2011005 的测试结果正常。
44.0a1-20150928 也测试正常。
https://developer.mozilla.org/en-US/docs/Extension_Versioning,_Update_and_Compatibility#Debugging_and_solving_problems

**Comment by yfdyh000** [comment]
题外话，目前放置xpi的方法，会使git库比较快的膨胀（每次500KB），使占用和clone大小增加。

**Comment by lychichem** [comment]
不知道两个文件具体的写法怎么样，update.rdf定义的版本号应该是要升级到的版本号吗？install.rdf应该是没有什么问题的，我感觉可能还是因为我这里下载都被fdm接管了

**Comment by lychichem** [comment]
那我删除一些git历史能减小git库的体积吗？@yfdyh000

**Comment by yfdyh000** [comment]
能，但以前的提交ID都变了，其他人得重新clone。以及，未来还是会膨胀，按现在的用法。

**Comment by yfdyh000** [comment]
另一种方法，用“存储”打包xpi，那样git就能有效压缩了。不过用户下载和拿到的就是1MB的xpi了。
印象中以前Mozilla推荐用“存储”打包xpi，现在不清楚是否还这样。

**Comment by lychichem** [comment]
在7z打包的时候设置为“存储”吗？但是二进制包的问题还是没解决，总觉得我如果用“存储”，这么直接push上去占用的空间会更大，如果git这个时候用delta更新还好，不是就惨了

**Comment by yfdyh000** [comment]
推送时会压缩的。文本明文拼接，git gc压缩后更有效率（等同固实压缩）。没测试过，但应该是这样。

**Comment by lychichem** [comment]
那我今天先删除旧版再重新打包一个看看，不过我这里现在github连接速度很成问题，不知道今晚/明早更新好之后能不能推上去，我不想发release也是这个原因

**Comment by yfdyh000** [comment]
https://git-scm.com/book/zh/v1/Git-%E5%B7%A5%E5%85%B7-%E9%87%8D%E5%86%99%E5%8E%86%E5%8F%B2 参考。
未来怎么发xpi，还没想好吧，继续发并且偶尔清空好像不太好，不方便以后。
目前才10MB，也不是很着急，只是个想法。
找个SS代理挂上。

奇怪，git gc后发现目前才3.5MB左右，这么小吗，有点超出我的预想，或许暂时没必要。

**Comment by lychichem** [comment]
但是一天500k也是增长的，git gc我刚才也用了两次，另外我会定期压缩git数据库
要不要整个其他的托管区，把下载链接指向那里，但是更新机制要求非加密连接要算hash就比较麻烦了，不过其实我git库是放在与onedrive同步的链接上，迁移更新链接倒并不难，只是onedrive回收站清空得辛苦微软了（现在网页版onedrive回收站里已经攒了50000+个文件……）
或者做一个脚本实时从我的git库build一个语言包出来也是个不错的想法
代理有灯，速度还可以，就是麻烦
git库小搞不好真的和我把git库放在onedrive文件夹有关系

**Comment by yfdyh000** [comment]
感觉可以再建一个Github项目，在那里放xpi。只是操作麻烦点。那个库大也就没关系了。

**Comment by lychichem** [comment]
我可以把xpi文件放onedrive上，只是我比较担心onedrive在国内的可访问性，别最后用户更新不了拉我出来背锅，如果这样我是丝毫不知情的，因为我是用hosts的，onedrive网页版总是可以访问

**Comment by lychichem** [comment]
刚才用7z测试了一下，不用list文件，不用特意指定zip格式，7z就能压缩出一个不含reeame和update.rdf的语言包xpi出来，这样我可以在这个repo里放个自动生成包的脚本，然后把生成好的包扔onedrive，更新链接也换成onedrive，这样就不用担心git库增长了

**Comment by yfdyh000** [comment]
onedrive的访问性不清楚，只是印象中觉得那个界面不是很好用。xpi自动更新怎么办呢。

**Comment by lychichem** [comment]
update.rdf把更新链接改一下就行了

**Comment by lychichem** [comment]
我想得太简单了，onedrive分享之后给出的链接带redirect，并不能直接指向文件真实的下载链接，所以是不能用的，估计还是得放git上，话说放在这个repo的另一个分支里会导致库增大吗？

**Comment by yfdyh000** [comment]
对的。感觉是会增大的，不过没有试过。Github Page不知道是否有特殊之处。以及，Github官方也推荐用Github Page而不是raw，见12306 DDOS事件。

**Comment by wenketel** [comment]
http://www.freehao123.com/baichuan-cdn/

要不试试这个

Date: Wed, 7 Oct 2015 08:58:18 -0700

**Comment by lychichem** [comment]
@wenketel 最好是加密连接的站点，否则按照[MDN文档](https://developer.mozilla.org/en-US/docs/Extension_Versioning%2C_Update_and_Compatibility#Securing_Updates)，我每次更新都要手动算一次hash，非常麻烦的

**Comment by wenketel** [comment]
那就  https://sta.sh  看看


Date: Wed, 7 Oct 2015 09:09:45 -0700

**Comment by lychichem** [comment]
@yfdyh000 用github自动生成了一个此repo的github page，但是还是要解决xpi的托管服务器的问题，不然还是会有麻烦

**Comment by yfdyh000** [comment]
我的意思就是，建一个 Firefox-zh-CN-locale-xpi 的单独Github库，把xpi都放在那里就好了。而且也不用删，反正删了也不减占用空间，整理好就可以。
