### ISSUE TITLE
由于开发人员工具部分的重大bug暂停维护

### ISSUE THREAD

**Issue by lychichem** [lychichem/Firefox-zh-CN-locale#16]
已知4月4日左右的更新造成了开发人员工具无法正常调用，现在查找原因中，可能会暂停更新相当长一段时间甚至完全从头开始，当然如果你能协助找到bug原因，这一进程会加快

**Comment by yfdyh000** [comment]
查到原因了，cmdSetdirManual3缺失，已测试确认。我也绕了些弯路，刚刚才发现浏览器控制台中的堆栈展开，右侧的里面有报错信息。

**Comment by lychichem** [comment]
奇怪了，今天测试就正常了，昨天我其实已经推送更新了，但不知道为啥就是出这个bug，可能昨天我nightly没更新成功而我更新了语言包吧……问题已解决，我现在本地新开了一个branch汉化devtools
