### ISSUE TITLE
证书错误页面无法显示hostname

### ISSUE THREAD

**Issue by lychichem** [lychichem/Firefox-zh-CN-locale#17]
已向bugzilla反馈（https://bugzilla.mozilla.org/show_bug.cgi?id=1263174 ），此bug与本语言包无关，可能是Firefox本身处理机制的问题。@yFdyh000 bugzilla那边能不能推动一下，我禁用语言包也是一样的效果（截图就是禁用语言包截的，应该能排除我本身翻译的问题）

**Comment by yfdyh000** [comment]
https://www.firefox.net.cn/ 目前没问题，如何重现。
48.0a1 (2016-04-06) 用 https://subdomain.preloaded-hsts.badssl.com/ 未见问题。

**Comment by yfdyh000** [comment]
用 48.0a1 (2016-04-08) 看到了，等我跑一下回归测试。

**Comment by lychichem** [comment]
bug1263174[https://bugzilla.mozilla.org/show_bug.cgi?id=1263174](url)已修复
