### ISSUE TITLE
项目的网址挂掉了

### ISSUE THREAD

**Issue by yfdyh000** [lychichem/Firefox-zh-CN-locale#18]
https://github.com/lychichem/Firefox-zh-CN-locale 和 http://lychichem.github.io/ 的 http://lychichem.github.io/langpack-release 404了。

**Comment by lychichem** [comment]
没毛病，我不再更新了，所以更新repo也就不存在了，这个网页自然404了

发送自我的 Windows 10 手机

发件人: YFdyh000<mailto:notifications@github.com>
发送时间: 2016年11月30日 4:28
收件人: lychichem/Firefox-zh-CN-locale<mailto:Firefox-zh-CN-locale@noreply.github.com>
主题: [lychichem/Firefox-zh-CN-locale] 项目的网址挂掉了 (#18)


https://github.com/lychichem/Firefox-zh-CN-locale 和 http://lychichem.github.io/ 的 http://lychichem.github.io/langpack-release 404了。

―

**Comment by yfdyh000** [comment]
嗯，发之后看到了。本来想通知一下 https://groups.google.com/forum/#!topic/mozilla.dev.l10n/-I1PYFOMKC8 (https://github.com/mozilla-l10n/firefox-aurora-langpacks) 的事情，不过刚也想到，本项目原本是每夜版吧，开发者版原本也每天更新，所以好像意义不大。
