### ISSUE TITLE
关于 20150708 的 redirectWindowsSearch

### ISSUE THREAD

**Issue by yfdyh000** [lychichem/Firefox-zh-CN-locale#4]
https://dxr.mozilla.org/ 的索引会有一天的延迟，所以暂时查不到。
http://mxr.mozilla.org/mozilla-central/search?string=redirectWindowsSearch 能查到
是 https://bugzilla.mozilla.org/show_bug.cgi?id=1177237

"使用此搜索引擎处理来自Windows的搜索"  我觉得还好吧。
根据 https://hg.mozilla.org/mozilla-central/rev/5d12635ce6be#l2.37 的注释，Windows 10的任务栏搜索是打开Bing并搜索该词，而这个选项的作用是提取搜索词并换成用户指定的默认搜索引擎来搜索。

"使用此搜索引擎处理通过 Windows 进行的搜索" 或许更清晰，但同样有歧义。
如果加上"任务栏"或许更清晰，但其他部分可能也能进行这样的搜索。
"...通过 Windows 组件进行的搜索" 如何，只是稍长并有演绎。

**Comment by lychichem** [comment]
这个功能如果是给win10用户开发的，那我现在就在win10上测试，并不能正常使用。

**Comment by yfdyh000** [comment]
总之注释是这么写的，先这么翻译就可以。
并不能正常使用也许正在开发？反正Nightly，崩溃都正常。
我这里暂时没装最新版的Win10，不知道旧版有没有这个功能。

**Comment by lychichem** [comment]
应该不会，bugzilla上已经标注为resolved fixed了，这样的至少功能应该已经实现了才对

发自我的 Windows Phone
________________________________
发件人: YFdyh000<mailto:notifications@github.com>
发送时间: ‎2015/‎7/‎9 0:31
收件人: lychichem/Firefox-zh-CN-locale<mailto:Firefox-zh-CN-locale@noreply.github.com>
抄送: Chi Lei<mailto:leichixian@outlook.com>
主题: Re: [Firefox-zh-CN-locale] 关于 20150708 的 redirectWindowsSearch (#4)

总之注释是这么写的，先这么翻译就可以。
并不能正常使用也许正在开发？反正Nightly，崩溃都正常。
我这里暂时没装最新版的Win10，不知道旧版有没有这个功能。

---

**Comment by yfdyh000** [comment]
偶尔也有返工或例外的情况，虽然并不常见。

我刚刚去测试了一下，确认正常使用。Nightly 20150708，新增并默认启用了此选项。
将搜索引擎改成Yahoo，在开始菜单中搜索111并回车，打开的是Yahoo进行搜索。
应该就是这样了吧，有哪里不对吗。你的Win10是不是有什么问题/特质……

**Comment by lychichem** [comment]
这个会不会和系统区域和语言设置之类的有关？我这里是中文windows10专业版10162，区域中国，语言简体中文，你是什么配置？

**Comment by yfdyh000** [comment]
那或许无关，我的是Windows 10 专业版 简体中文版 区域中国，版本大概10074（以前装的）。
源代码好像并没有什么特别的地方，只是判断是否为win10。
你那里哪里不正常，是没有这个选项，还是仍启动了Bing搜索，还是其他什么症状？
将Nightly设置为默认浏览器，启用该选项（默认启用），默认搜索引擎改成非Bing，按Win按111按回车。

**Comment by lychichem** [comment]
启动的仍然是bing，选项是有的，nightly已是默认浏览器，默认搜索引擎是google

**Comment by yfdyh000** [comment]
那就奇怪了。默认引擎改成Yahoo试试，Google当时我没试。

**Comment by lychichem** [comment]
新建配置，默认yahoo，搜索栏输入222，回车，打开的仍是bing
![default](https://cloud.githubusercontent.com/assets/9316590/8588767/e0693ac4-2640-11e5-9129-3d57aee7bb57.PNG)

**Comment by yfdyh000** [comment]
那就很奇怪了，不知道你那里有什么特殊情况。

**Comment by lychichem** [comment]
我去查了一下源码，他们的替换策略是替换以https://www.bing.com/search开头的链接，所以我想知道你那里任务栏搜索时提交的链接是cn.bing.com开头的还是www.bing.com开头的，因为你知道，微软是检测用户的ip来提供国家区别页面的

**Comment by yfdyh000** [comment]
确认是 https://www.bing.com/search 开头的，然后是搜索词以及后面一些参数。
这种国别域名一般是通过用户IP等信息重定向的（比如bing.com当前就是这样），不会在系统中写死。
你可以用任务管理器-详细信息，右击列-选择列，把命令行选上，悬停看看Nightly的命令行怎么回事。

**Comment by lychichem** [comment]
我这边确认是以cn.bing.com开头的，无论是否启用cortana都一样，看来和我在bugzilla那里的回复是一致的，然而我用了gae也无法切换这个链接到www.bing.com，但我记得这个是ip相关的

发自我的 Windows Phone
________________________________
发件人: YFdyh000<mailto:notifications@github.com>
发送时间: ‎2015/‎7/‎9 14:09
收件人: lychichem/Firefox-zh-CN-locale<mailto:Firefox-zh-CN-locale@noreply.github.com>
抄送: Chi Lei<mailto:leichixian@outlook.com>
主题: Re: [Firefox-zh-CN-locale] 关于 20150708 的 redirectWindowsSearch (#4)

确认是 https://www.bing.com/search 开头的，然后是搜索词以及后面一些参数。
这种国别域名一般是通过用户IP等信息重定向的（比如bing.com当前就是这样），不会在系统中写死。
你可以用任务管理器-详细信息，右击列-选择列，把命令行选上，悬停看看Nightly的命令行怎么回事。

---

**Comment by lychichem** [comment]
Bugzilla已提出修复bug：https://bugzilla.mozilla.org/show_bug.cgi?id=1182308
