### ISSUE TITLE
搜索引擎

### ISSUE THREAD

**Issue by lychichem** [lychichem/Firefox-zh-CN-locale#5]
修改了amazon.cn但是加载失败，@yfdyh000 你知道这个语言包里的搜索引擎的加载机制，因为百度我也是改过的，直接复制了改过的文件过来没问题的

**Comment by yfdyh000** [comment]
我测试好像没有问题，似乎是加载了，但又不很确定。
如果没加载，改个ID试试？比如文件名和list中改成 amazondotcn1。
用户删掉的ID就存起来了，在search-metadata.json。

**Comment by lychichem** [comment]
我提交了一个新版本，现在amazon搜索可以显示在选项的搜索设置里了，搜索结果页面也是加密的，但是搜索建议没法用

**Comment by yfdyh000** [comment]
用 Web 控制台调试网页的请求，浏览器控制台-网络 调试浏览器的请求，找出不同点。
搜索引擎的参数应该尽量精简。有些可能是访问源跟踪（比如`client=amazon-search-ui`指来自搜索框）乃至推广分成（我担心这个；除非是Mozilla官方的参数id），应该去掉。

`<Url type="application/x-suggestions+json" method="GET" template="https://completion.amazon.cn/search/complete?method=completion&amp;mkt=3240&amp;search-alias=aps&amp;q={searchTerms}"/>`
应该就没问题了。

**Comment by lychichem** [comment]
可以了，感谢感谢，另外官方版语言包有类似的加密化搜索引擎计划吗？

**Comment by yfdyh000** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1104532 最近更新了简体中文的搜索引擎，但并不涉及亚马逊。
https://bugzilla.mozilla.org/show_bug.cgi?id=1069123 将维基百科换为HTTPS
https://bugzilla.mozilla.org/show_bug.cgi?id=958886 将亚马逊改为HTTPS，不过只是英文版。

http://hg.mozilla.org/l10n-central/zh-CN/file/tip/browser/searchplugins/amazondotcn.xml 的确还是http，看来可考虑弄个补丁。但应该参考英文版去改，加上Mozilla的sourceid。

其他语言的bug好像是 https://bugzilla.mozilla.org/show_bug.cgi?id=1179332 所属。

**Comment by lychichem** [comment]
英文亚马逊那个我试了，并没有加密

发自我的 Windows Phone
________________________________
发件人: YFdyh000<mailto:notifications@github.com>
发送时间: ‎2015/‎7/‎29 17:21
收件人: lychichem/Firefox-zh-CN-locale<mailto:Firefox-zh-CN-locale@noreply.github.com>
抄送: Chi Lei<mailto:leichixian@outlook.com>
主题: Re: [Firefox-zh-CN-locale] 搜索引擎 (#5)

https://bugzilla.mozilla.org/show_bug.cgi?id=1104532 最近更新了简体中文的搜索引擎，但并不涉及亚马逊。
https://bugzilla.mozilla.org/show_bug.cgi?id=1069123 将维基百科换为HTTPS
https://bugzilla.mozilla.org/show_bug.cgi?id=958886 将亚马逊改为HTTPS，不过只是英文版。

http://hg.mozilla.org/l10n-central/zh-CN/file/tip/browser/searchplugins/amazondotcn.xml 的确还是http，看来可考虑弄个补丁。但应该参考英文版去改，加上Mozilla的sourceid。

其他语言的bug好像是 https://bugzilla.mozilla.org/show_bug.cgi?id=1179332 所属。

---

**Comment by yfdyh000** [comment]
见 https://hg.mozilla.org/mozilla-central/file/b6ebb4cba9e1/browser/locales/en-US/searchplugins/amazondotcom.xml ，https并没有问题
https://completion.amazon.com/search/complete?q=1&search-alias=aps&mkt=1 经测也并没有问题

注意，bug 958886在23小时前登陆补丁。我这里的42.0a1 (2015-07-28)经测，没有问题，搜索和建议都是https请求。
