### ISSUE TITLE
协助请求

### ISSUE THREAD

**Issue by lychichem** [lychichem/Firefox-zh-CN-locale#7]
@wenketel @yfdyh000 @tiansh 语言包中新增的三个文件术语量太大，翻译有困难，请求支持，具体是https://github.com/lychichem/Firefox-zh-CN-locale/blob/eac74d56f98df9cf139913c929f19a05f1bd218b/browser/chrome/zh-CN/locale/browser/devtools/markers.properties ，https://github.com/lychichem/Firefox-zh-CN-locale/blob/eac74d56f98df9cf139913c929f19a05f1bd218b/browser/chrome/zh-CN/locale/browser/devtools/performance.dtd 和https://github.com/lychichem/Firefox-zh-CN-locale/blob/eac74d56f98df9cf139913c929f19a05f1bd218b/browser/chrome/zh-CN/locale/browser/devtools/performance.properties （第三个有一个原有文件的字串和它很接近，我抄过来用了一下）

**Comment by wenketel** [comment]
yf动作略快，我安装试试看看。
